server:
  port: ${SERVER_PORT}  # 팀 전용 포트

spring:
  application:
    name: javara
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}  # 환경 변수로 설정
    password: ${DB_PASSWORD}  # 환경 변수로 설정
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      leak-detection-threshold: 120000
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  #이미지관련
  file:
    directory: /home/t25111/img
    serverImageUrl: ${SERVER_IMAGE_URL}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExpiration: ${ACCESS_EXP}
    refreshExpiration: ${REFRESH_EXP}

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tags-sorter: alpha
    display-request-duration: true

# 백업 설정
app:
  backup:
    directory: /home/t25111/backup
    mysqldump:
      path: mysqldump
    schedule: 0 0 1 * * *
    # 매일 1시마다 테스트로 백업(초 분 시 일 월 요일)
